# Generated by Django 2.0.5 on 2018-06-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='activity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_des',
            field=models.CharField(max_length=100),
        ),
    ]
