# Generated by Django 2.0.5 on 2018-06-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20180601_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='cost',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='items',
            name='unit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='items',
            name='visibility',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
