# Generated by Django 2.0.5 on 2018-06-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20180604_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='inno',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='items',
            name='pdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='pono',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='items',
            name='rdate',
            field=models.DateField(null=True),
        ),
    ]
