# Generated by Django 2.0.5 on 2018-06-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20180604_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='inno',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='pono',
            field=models.IntegerField(null=True),
        ),
    ]
