# Generated by Django 2.0.5 on 2018-06-05 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20180601_1139'),
        ('inventory', '0005_auto_20180604_1121'),
    ]

    operations = [
    ]
