# Generated by Django 2.0.5 on 2018-06-11 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20180605_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_des', models.CharField(max_length=100)),
                ('item_code', models.CharField(max_length=100)),
                ('activity', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('cost', models.IntegerField(null=True)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('visibility', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locode', models.IntegerField(null=True)),
                ('pono', models.IntegerField(null=True)),
                ('inno', models.IntegerField(null=True)),
                ('pdate', models.DateField(null=True)),
                ('rdate', models.DateField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='items',
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.parent'),
        ),
    ]
