# Generated by Django 2.0.5 on 2018-06-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20180611_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='reciept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locode', models.IntegerField(null=True)),
                ('pono', models.IntegerField(null=True)),
                ('inno', models.IntegerField(null=True)),
                ('pdate', models.DateField(null=True)),
                ('rdate', models.DateField(null=True)),
                ('num', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='child',
            name='parent',
        ),
        migrations.AddField(
            model_name='child',
            name='rec_no',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='parent',
        ),
    ]
