# Generated by Django 2.0.5 on 2018-06-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20180611_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='activity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='child',
            name='item_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='child',
            name='item_des',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='child',
            name='unit',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='child',
            name='visibility',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
