# Generated by Django 2.0.5 on 2018-06-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20180612_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='location',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
