# Generated by Django 2.0.5 on 2018-06-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20180612_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='activity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='item_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='item_des',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='loc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='rec_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='inno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='locode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='pdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='pono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='rdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
