# Generated by Django 2.0.5 on 2018-05-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpemployee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpemployee',
            name='employee_number',
            field=models.IntegerField(default='30084769'),
        ),
    ]
