# Generated by Django 2.0.5 on 2018-05-17 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hpemployee', '0002_hpemployee_employee_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpemployee',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
