# Generated by Django 2.0.5 on 2018-05-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpemployee', '0004_hpemployee_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpemployee',
            name='DOB',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='hpemployee',
            name='employee_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hpemployee',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
