# Generated by Django 2.0.5 on 2018-05-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpemployee', '0005_auto_20180521_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpemployee',
            name='DOB',
            field=models.CharField(max_length=100),
        ),
    ]
