# Generated by Django 2.0.5 on 2018-05-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpemployee', '0006_auto_20180523_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpemployee',
            name='Email_id',
            field=models.CharField(default='gnhegde@hpcl.in', max_length=100),
        ),
        migrations.AddField(
            model_name='hpemployee',
            name='Phone_Number',
            field=models.IntegerField(default='9920635887'),
        ),
        migrations.AlterField(
            model_name='hpemployee',
            name='DOB',
            field=models.DateField(max_length=100),
        ),
    ]
