# Generated by Django 2.0.5 on 2018-05-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpemployee', '0008_auto_20180523_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpemployee',
            name='employee_number',
            field=models.IntegerField(max_length=7),
        ),
    ]
