# Generated by Django 2.0.5 on 2018-05-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpemployee', '0009_auto_20180523_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hpemployee',
            name='location',
        ),
        migrations.AddField(
            model_name='hpemployee',
            name='location_code',
            field=models.IntegerField(default=10141),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hpemployee',
            name='Email_id',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hpemployee',
            name='Phone_Number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hpemployee',
            name='employee_number',
            field=models.IntegerField(),
        ),
    ]
