# Generated by Django 2.0.5 on 2018-05-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpemployee', '0010_auto_20180528_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpemployee',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
