# Generated by Django 2.0.5 on 2018-05-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpemployee', '0011_hpemployee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpemployee',
            name='last_login',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
