# Generated by Django 2.0.5 on 2018-06-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpemployee', '0013_hpemployee_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpemployee',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
