# Generated by Django 2.0.5 on 2018-06-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpemployee', '0014_auto_20180601_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpemployee',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
