# Generated by Django 2.0.5 on 2018-06-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpemployee', '0015_hpemployee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpemployee',
            name='last_login',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
    ]
