# Generated by Django 2.0.5 on 2018-06-05 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hpemployee', '0016_auto_20180604_1112'),
        ('hpemployee', '0012_auto_20180529_1635'),
    ]

    operations = [
    ]
