# Generated by Django 2.0.5 on 2018-06-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpemployee', '0017_merge_20180605_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpemployee',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hpemployee',
            name='DOB',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hpemployee',
            name='last_login',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
    ]
